### ISSUE TITLE
Gerar exception personalizada

### ISSUE THREAD

**Issue by pedrolauro15** [antonielliimma/ddev-pg#1]
Gerar excessão personalizada quando ocorrer um erro de banco de dados.
Ex: SequelizeDatabaseError quando os processos do sequelize retornam exception.

Tal processo facilita no tratamento de erros, pode-se capturar a excessão personalizada e fazer um tratamento específico de erro.

**Comment by antonielliimma** [comment]
@pedrolauro15 muito obrigado pela sugestão!

A partir da versão 1.0.12 esta disponível a exception DatabaseError.
